### PR TITLE
Create starts_with plugin

### PR DESCRIPTION
**Pull request by decal**
I created a plugin that adds to the result list the concatenation of the first X letters from the first name and the first Y letters from the last name where X is half the length of the first name and Y is half the length of the last name..

### CODE REVIEW

**Comment by jseidl** [comment]
Nice plug-in. Thanks for the contribution

**Comment by decal** [comment]
My pleasure..  I forgot to document it in the `README.md` the first time, so I made a second pull request.. can you accept it, please?

**Comment by jseidl** [comment]
Done! If you want you can add a CONTRIBUTORS.md file with your name on it, as I and the community sure appreciate your effort and shall not go unnoticed. Here's an example https://github.com/caolan/nodeunit/blob/master/CONTRIBUTORS.md

**Comment by decal** [comment]
On Mon, 30 Apr 2018, Jan Seidl wrote:

Done.. merge please.. :-)

> Done! If you want you can add a CONTRIBUTORS.md file with your name on it, as I and the community sure appreciate your effort and shall not go unnoticed. Here's an example https://github.com/caolan/nodeunit/blob/master/CONTRIBUTORS.md
>
>

Derek Callaway <decal (AT) sdf {D0T} org>
Digital Security Consultant
PGP Key Mailed By Request [ 3264R/DCB1BB0A 2017-08-12 expires: 2019-06-03 ]
Public Fingerprint: [ C4CF 2E3E A17C B7E9 42DB  902C F059 0978 DCB1 BB0A ]

**Pull request merged**
